services:
  ansible_host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./inventory.yml:/usr/svc/inventory.yml"
      - "./playbooks:/usr/svc/playbooks"
    stdin_open: true
    tty: true
    networks:
      app_net:
        ipv4_address: 172.0.0.10
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - PUBLIC_KEY=yourpublickey #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=brtsys #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=brtsys #optional
      - LOG_STDOUT= #optional
    volumes:
      - /path/to/openssh-server/config:/config
    ports:
      - 80:80
      - 2222:2222
    restart: unless-stopped

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
