services:
  ansible_host:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./inventory.yml:/usr/svc/inventory.yml"
      - "./playbooks:/usr/svc/playbooks"
    stdin_open: true
    tty: true
    networks:
      app_net:
        ipv4_address: 172.0.0.10
  test_pc:
    # https://hub.docker.com/r/linuxserver/openssh-server
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: test_pc
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=/usr/svc/.ssh/ssh_client_key.pub #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=false #optional
      - USER_PASSWORD=sudo_pw #optional
      # - USER_NAME=test_user #optional. defaults to 'linuxserver.io'
    volumes:
      - "./ssh_keys:/usr/svc/.ssh"
    ports:
      - 2222:2222
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.0.0.11
    # command: [/bin/bash, "-c", "apk update && apk add --update --no-cache python3 && /bin/bash"]

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
